### PR TITLE
Updating code.storageos.net to github

### PR DESCRIPTION
**Pull request by angelos-p**

### CODE REVIEW

**Comment by andrelucas** [comment]
No, that's wrong - the c2 source code is in package code.storageos.net and won't compile if you change this.

**Comment by andrelucas** [comment]
c2 is pinned to a particular version of service, so a PR won't take effect. when the pin is moved, though, this change will comprehensively break the c2 build.

**Comment by angelos-p** [comment]
Yes c2 will need to be updated as well and only then update to the new pin. I am planning to move on to c2 after I confirm that this works fine first.

This PR is there to unblock t2.

**Comment by angelos-p** [comment]
The pin won't be able to be updated on c2 anyway since code.storageos.net doesn't exist anymore.

**Comment by szank** [comment]
I am OK with these changes, but let's do it right. 
We should bump the go version to 1.6.x and use go modules here. 

I'd be happy to assist. There might be a few bumps in the road. 
I have a hunch that the CP would continue to work (given the replace directive already in master) when we contribute to this repo without any additional changes but we could also bite the bullet and make it right. 

FWIW when we switch to the go modules, we'll have to properly git tag every new change to the proto files here but that's for the better I think.

**Pull request closed without merging**
